version: '3.8'

services:
  app:
    image: php:7.4
    container_name: laravel58
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: bash -c "composer install --ignore-platform-reqs -vvv"

