version: '3.8'

services:
  app:
    build: .
    container_name: laravel58
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:80 -t public
