version: '3.8'

services:
  app:
    build: .
    container_name: laravel58
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "80:80"
    command: php artisan serve --host=0.0.0.0 --port=80
